mkfs.vfat: enforce the number of clusters to one
In recent mkfs.vfat versions this value is selected to a different
value than one, and therefore the generation of the images with fat16copy.py
fails:
"""
AssertionError: Can only handle FAT with 1 reserved sector
"""

So, ensure the generated FAT volume only contains one reserved sector.

https://jira.digi.com/browse/ADK4A-1384

Signed-off-by: Isaac Hermida <isaac.hermida@digi.com>